services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: auditra
      POSTGRES_PASSWORD: auditra
      POSTGRES_DB: auditra
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auditra"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
