"""model registration tables

Revision ID: 0001
Revises:
Create Date: 2026-10-04 02:27:49.299642

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "model_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", "value", name="uq_model_tags_tenant_key_value"),
    )
    op.create_table(
        "model_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("model_type_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("native_model_id", sa.String(length=512), nullable=False),
        sa.Column("canonical_key", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_name", sa.String(length=255), nullable=True),
        sa.Column("owner_contact", sa.String(length=512), nullable=True),
        sa.Column("team_name", sa.String(length=255), nullable=True),
        sa.Column("hosting_mode", sa.String(length=64), nullable=True),
        sa.Column("runtime_hint", sa.String(length=64), nullable=True),
        sa.Column(
            "lifecycle_state", sa.String(length=32), server_default="REGISTERED", nullable=False
        ),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_reference", sa.String(length=512), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "lifecycle_state IN ('REGISTERED', 'ACTIVE', 'DEPRECATED', 'RETIRED', 'ARCHIVED')",
            name="ck_models_lifecycle_state",
        ),
        sa.ForeignKeyConstraint(
            ["model_type_id"],
            ["model_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["model_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "canonical_key", name="uq_models_tenant_canonical_key"),
    )
    op.create_index(op.f("ix_models_tenant_id"), "models", ["tenant_id"], unique=False)
    op.create_index(
        "ix_models_tenant_id_created_at",
        "models",
        ["tenant_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_models_tenant_id_lifecycle_state",
        "models",
        ["tenant_id", "lifecycle_state"],
        unique=False,
    )
    op.create_index(
        "ix_models_tenant_id_model_type_id", "models", ["tenant_id", "model_type_id"], unique=False
    )
    op.create_index(
        "ix_models_tenant_id_native_model_id",
        "models",
        ["tenant_id", "native_model_id"],
        unique=False,
    )
    op.create_index(
        "ix_models_tenant_id_provider_id", "models", ["tenant_id", "provider_id"], unique=False
    )
    op.create_index(
        "ix_models_tenant_id_updated_at",
        "models",
        ["tenant_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "model_tag_links",
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["model_tags.id"],
        ),
        sa.PrimaryKeyConstraint("model_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_tag_links")
    op.drop_index("ix_models_tenant_id_updated_at", table_name="models")
    op.drop_index("ix_models_tenant_id_provider_id", table_name="models")
    op.drop_index("ix_models_tenant_id_native_model_id", table_name="models")
    op.drop_index("ix_models_tenant_id_model_type_id", table_name="models")
    op.drop_index("ix_models_tenant_id_lifecycle_state", table_name="models")
    op.drop_index("ix_models_tenant_id_created_at", table_name="models")
    op.drop_index(op.f("ix_models_tenant_id"), table_name="models")
    op.drop_table("models")
    op.drop_table("model_types")
    op.drop_table("model_tags")
    op.drop_table("model_providers")
    # ### end Alembic commands ###
